"circumference"= "num_columns" * ( "ball_safety_size" + "inbetween_wall_thickness" )
"ball_safety_size"= 6mm + 2 * "ball_offset"
"ball_offset"= .01
"center_column_diameter"= "circumference" / ( 3.14159 )
"D2@Sketch2"="center_column_diameter"
"outer_wall_thickness"= .6mm
"inner_wall_thickness"= 2.5mm
"inbetween_wall_thickness"= .8mm
"D5@Sketch2"="inbetween_wall_thickness"*2/3
"D4@Sketch2"="inner_wall_thickness"
"num_columns"= 85
"column_height"= int ( "center_column_diameter" / "num_sections" * 8 ) / 8
"D1@Boss-Extrude1"="column_height"
"D1@CirPattern1"="num_columns"
"D1@Sketch5"="center_column_diameter"/2
"D5@Sketch5"="inner_wall_thickness"/2
"D1@Sketch2"="ball_safety_size"
"num_sections"= 3
"nut_slot_feature_thicknes"= 0.1875
"D1@Sketch7"="nut_slot_feature_thicknes"
"D19"= "nut_slot_feature_thicknes"
"num_interfaces"= 8
"D1@Cut-Extrude1"="nut_slot_feature_thicknes"
"D2@Cut-Extrude1"="nut_slot_feature_thicknes"
"D1@Sketch11"=360 / "num_interfaces"
"D5@Sketch13"=360/("num_interfaces"*2)*2/3
"D1@CirPattern6"="num_interfaces"
"D7@Sketch2"=6mm
"dowel_clearance"= .14
"D1@Sketch16"="dowel_clearance"
"dowel_tight"= 0.13
"D1@Sketch13"="dowel_tight"
